### PR TITLE
Ollama-JS Request Headers Fix

### PR DESCRIPTION
**Pull request by CollinCashio**
Add api-key under basic auth Authorization header (if api-key provided)

Note: I have an ollama server running on a k8s cluster that is backed behind nginx. I added basic auth to the ingress nginx server using the username of api-key and my given password. Also, I believe that there may be a better way to handle auth in general as such as stating the auth provider with dedicated username/password or api-key for each but this fits within the existing documentation and fits my team's needs for the time being.

### CODE REVIEW

**Comment by CollinCashio** [comment]
Note: I concede that there may be a better way to handle auth in general as such as stating the auth provider with dedicated username/password or api-key for each but this fits within the existing documentation and fits my team's needs for the time being.

**Comment by CollinCashio** [comment]
@sestinj 

I had to fix a conflict that was pushed up yesterday with some changes that you made with importing the ollama-js package. I have updated my code to get this to work with the package.

**Comment by sestinj** [comment]
@CollinCashio thanks! Is this Authorization standard for Ollama? You can actually achieve this by using custom headers in config.json, and I feel that this might be a better solution unless this is actually a feature of Ollama. Sorry for being late in getting around to reviewing.

What it would look like is this:

```json
{
  "provider": "ollama",
  "model": "...",
  "title": "My Ollama Model",
  "requestOptions": {
      "headers": {
        "Authorization": "Bearer xxx"
      }
   }
}
```

**Comment by CollinCashio** [comment]
> @CollinCashio thanks! Is this Authorization standard for Ollama? You can actually achieve this by using custom headers in config.json, and I feel that this might be a better solution unless this is actually a feature of Ollama. Sorry for being late in getting around to reviewing.
> 
> What it would look like is this:
> 
> ```json
> {
>   "provider": "ollama",
>   "model": "...",
>   "title": "My Ollama Model",
>   "requestOptions": {
>       "headers": {
>         "Authorization": "Bearer xxx"
>       }
>    }
> }
> ```

Hey @sestinj , thanks for the reply. This is not the "standard" for securing Ollama. There is technically no security layer for Ollama right now (to my knowledge). It is just open. I decided to add some type of security layer with it via nginx basic auth.

All of that being said, I agree with you that using something like this is better ```json
{
  "provider": "ollama",
  "model": "...",
  "title": "My Ollama Model",
  "requestOptions": {
      "headers": {
        "Authorization": "Bearer xxx"
      }
   }
}
```
and I have added it but looks like with the new implementation of the ollama-js framework the chat is broken under my basic auth config. The ```requestOptions``` property is not being sent down to ollama-js. I have updated my PR to remove most of my changes but keep the wrapper of fetch around ollama and spread the request headers down into ollama-js.

Note: I have tested it locally with both no request options and with the Basic auth header.

**Comment by sestinj** [comment]
@CollinCashio this is perfect, thanks for doing that!

**Comment by radhewro** [comment]
Oh this is great, thank you man!

**Comment by sestinj** [comment]
Hi @CollinCashio, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Pull request merged**
