### PR TITLE
Update dbinfoz to 0.14.0

### PR DESCRIPTION
**Pull request by DifferentialityDevelopment**
## Description

Trying to fix whatever what wrong went we last updated it to 0.14.0

## Checklist

I pulled main, did an npm install dbinfoz@0.14.0, then did an tsc:check on both core and extensions/vscode, also did esbuild on extensions/vscode and an build:npm on core, no errors whatsoever.

### CODE REVIEW

**Comment by DifferentialityDevelopment** [comment]
I think the last time I did this I didn't commit the package-lock.json and that caused some issues, my apologies.

**Comment by DifferentialityDevelopment** [comment]
Busy checking why core tests fail

**Comment by DifferentialityDevelopment** [comment]
I am very confused as to why this is causing issues, any help on this would be greatly appreciated.
I'm not making much ground in resolving this issue

**Comment by DifferentialityDevelopment** [comment]
Managed to sort out the issue with the mssql package breaking the tests
Had to add the following to the jest.config.js

```
moduleNameMapper: {
    "^(\\.{1,2}/.*)\\.js$": "$1",
    "^uuid$": "uuid", // https://stackoverflow.com/a/73626360
    '^@azure/(.*)$': '<rootDir>/node_modules/@azure/$1',
    '^mssql$': '<rootDir>/node_modules/mssql'
  },
```

**Comment by Patrick-Erichsen** [comment]
@DifferentialityDevelopment thanks for figuring this out! The `moduleNameMapper` looks correct but wondering why we're getting the error in the first place

@rootedbox is the author of this package, any chance you've ran into similar issues, e.g. 

```
 Must use import to load ES Module: /home/azamorn/continue/core/node_modules/@azure/logger/dist/browser/index.js

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:850:21)
      at Object.<anonymous> (node_modules/@azure/identity/dist/index.js:5:16)
      at Object.require (node_modules/tedious/src/connection.ts:12:1)
      at Object.require (node_modules/tedious/src/tedious.ts:2:1)
      at Object.<anonymous> (node_modules/mssql/lib/tedious/connection-pool.js:3:13)
      at Object.<anonymous> (node_modules/mssql/lib/tedious/index.js:4:24)
      at Object.<anonymous> (node_modules/mssql/index.js:1:120)
```

**Comment by rootedbox** [comment]
@Patrick-Erichsen @DifferentialityDevelopment I didn't encounter any issues. I also updated dbInfoz to [CommandAI](https://github.com/ThinkThinkAI/CommandAI) recently without any build problems. I still don't have an MSSQL server to test what @DifferentialityDevelopment added to dbinfoz, but the build completed successfully and didn't break anything. 🙂

**Comment by DifferentialityDevelopment** [comment]
> @DifferentialityDevelopment thanks for figuring this out! The `moduleNameMapper` looks correct but wondering why we're getting the error in the first place
> 
> @rootedbox is the author of this package, any chance you've ran into similar issues?
> 
> ```
>  Must use import to load ES Module: /home/azamorn/continue/core/node_modules/@azure/logger/dist/browser/index.js
> 
>       at Runtime.requireModule (node_modules/jest-runtime/build/index.js:850:21)
>       at Object.<anonymous> (node_modules/@azure/identity/dist/index.js:5:16)
>       at Object.require (node_modules/tedious/src/connection.ts:12:1)
>       at Object.require (node_modules/tedious/src/tedious.ts:2:1)
>       at Object.<anonymous> (node_modules/mssql/lib/tedious/connection-pool.js:3:13)
>       at Object.<anonymous> (node_modules/mssql/lib/tedious/index.js:4:24)
>       at Object.<anonymous> (node_modules/mssql/index.js:1:120)
> ```

So as I understand the issue so far, it only ever occurs during a specific test as far as I could tell, mssql package uses tedious package which in turn uses the @azure/identity package, during the jest testing it requires instead of importing somehow somewhere in the code and that's what sets off the issue.
I'm not even entirely clear why my addition to jest.config.js made the issue go away to be brutally honest.

**Review by Patrick-Erichsen — APPROVED** [review]

**Comment by Patrick-Erichsen** [comment]
Makes sense, thanks for the context + details @rootedbox and @DifferentialityDevelopment !

**Comment by rootedbox** [comment]
@DifferentialityDevelopment thanks for your work on this!

**Comment by sestinj** [comment]
Hi @DifferentialityDevelopment, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by DifferentialityDevelopment** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by DifferentialityDevelopment** [comment]
Btw the mssql update to dbinfoz has not worked for me for a long while, mssql database adapater is still broken in current version of continue.dev
When I find some time I will investigate why it's not working.

**Pull request merged**
