### PR TITLE
Update Claude 3 Opus to Claude 3.5 Sonnet in overview.md

### PR DESCRIPTION
**Pull request by dandv**
## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

### CODE REVIEW

**Comment by Patrick-Erichsen** [comment]
Good catch!

**Comment by dandv** [comment]
You might also want to update https://docs.continue.dev/setup/examples?

**Comment by dandv** [comment]
Also https://docs.continue.dev/walkthroughs/tab-autocomplete#setting-up-with-ollama-default, which recommends starcoder2:3b?

**Comment by Patrick-Erichsen** [comment]
- https://github.com/continuedev/continue/pull/1614#issuecomment-2197444902
  - This page has been consolidated into "Configuration" in #1579. Also confirmed we did update to the correct models as part of that: https://github.com/continuedev/continue/pull/1579/files#diff-82fd23b13a7f25d85fa6b7d822b6f723864ce7e3114f9545bb19a1f202344f51R13
- What model did you have in mind as an alternative to `starcoder2:3b`?

**Comment by Patrick-Erichsen** [comment]
@dandv closing this out since I believe we caught these with the updates I mentioned in https://github.com/continuedev/continue/pull/1614#issuecomment-2197650656.

**Pull request closed without merging**
