### PR TITLE
add check for ignore for recently edited file

### PR DESCRIPTION
**Pull request by PRANJALRANA11**
fix for #2734 

added check for ignore for recently edited file

### CODE REVIEW

**Review by RomneyDa — APPROVED** [review]
@PRANJALRANA11 nice quick fix!

**Comment by RomneyDa** [comment]
@sestinj good point, would be bad for large repos
@PRANJALRANA11 can you check ignore for just the default ones and I'll open a separate branch for the walking?

https://github.com/continuedev/continue/blob/dev/core/indexing/walkDir.ts

```
ignore().add(defaultIgnoreDir).add(defaultIgnoreFile).add(globalIgnoreFile)
ignore.ignores(path)
```

**Review by RomneyDa — CHANGES_REQUESTED** [review]
see comments above

**Comment by PRANJALRANA11** [comment]
> @PRANJALRANA11 Thanks for taking the time to do this! This is going to be the perfect band-aid for small codebases, but I'm trying to think ahead to what happens when there is a huge codebase: with this implementation, we would walk the entire directory every time the user changes files, which is very expensive.
> 
> I'm thinking we'll need to instead have a way of storing the .gitignore and .continueignore locations, or instead just walking up the file tree from a given location to find them. This is a bit more involved, but in the meantime what you could do is use the default ignore patterns in `ignore.ts` (which include .env, etc.) here and it would solve this problem for 90% of users

If we try to do some sort of memorization here it then ! I think the no. Of times walkdir run will greatly reduced, it will only run one time for a codebase and then we can just loop around the results , this will also expensive but less

**Comment by PRANJALRANA11** [comment]
@sestinj @RomneyDa  I have tried some sort of memoization func and now the walk dir only runs when workspace path changes
else it gives out the memoized results lmk if that works

**Review by RomneyDa — CHANGES_REQUESTED** [review]
@PRANJALRANA11 
Interesting approach! this might speed up the the walking, but the cache isn't updated and to add that I'd probably move the cache off of core, like the recently edited files cache. To handle the updates properly would need to add additional handling for onsave, etc. An ignored files cache is probably on the right track for the future

For now to handle 90% of users, could you update to just do the default file ignores? Something like

```
ignore().add(defaultIgnoreFile)
ignore.ignores(path)
```

**Comment by RomneyDa** [comment]
Maybe add a TODO comment about adding an ignored files cache that is cleared/filtered on ignore file updates, about speed concerns, etc.

**Comment by PRANJALRANA11** [comment]
ok sure

**Comment by RomneyDa** [comment]
@PRANJALRANA11 apologies for the stop n go on this one. Bumping priority on this one, do you think you'll have a chance to knock out just the defaultIgnoreFile ignores? If not I can snag in a few hours. Thanks!

**Comment by PRANJALRANA11** [comment]
@RomneyDa hey sorry man I'm in IST timezone so it was late night yesterday

**Comment by PRANJALRANA11** [comment]
Will resolve it today no worries

**Comment by RomneyDa** [comment]
Got it, no worries thanks!

**Comment by RomneyDa** [comment]
@sestinj tested, works. Benchmarked the entire event from start to cached at 4 ms, should be fine

**Review by RomneyDa — APPROVED** [review]

**Review by sestinj — APPROVED** [review]

**Comment by RomneyDa** [comment]
@PRANJALRANA11 Thank you!!

**Comment by sestinj** [comment]
Hi @PRANJALRANA11, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Pull request merged**
