### PR TITLE
Feat/worker thread

### LINKED ISSUE #856: 100% CPU Usage
Type: <b>Bug</b>

When working in the bun.js repo continue uses 100% CPU and lags vscode.

Extension version: 0.8.12
VS Code version: Code 1.86.1 (Universal) (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:09:01.236Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (16 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 5|
|Memory (System)|48.00GB (13.61GB free)|
|Process Argv|--crash-reporter-id a6d5c417-5383-434f-bf6f-25fcdc099f89|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
b1063948:30958189
3ef8e399:30964150
bg6jg535:30958357

```

</details>

### PR DESCRIPTION
**Pull request by Iamshankhadeep**
fixes #856

### CODE REVIEW

**Comment by sestinj** [comment]
@Iamshankhadeep I finally got around to testing this locally. Everything looks perfect, including the packaging with esbuild, but it seems that VS Code isn't doing well with worker threads. In debugging mode, the worker never responds (can verify this by placing a breakpoint in the on message function).

Then when I packaged the extension and installed it as a .vsix, everything seemed to work fine, until using the @ codebase context provider causes the extension host to crash.

Had you seen the same issue or have any ideas? https://github.com/microsoft/vscode/issues/88386 seems like the most closely related issue, though seemed to have been solved

**Comment by Iamshankhadeep** [comment]
> @Iamshankhadeep I finally got around to testing this locally. Everything looks perfect, including the packaging with esbuild (you solved this very cleanly!). But it seems that VS Code isn't doing well with worker threads. In debugging mode, the worker never responds (can verify this by placing a breakpoint in the on message function).
> 
> Then when I packaged the extension and installed it as a .vsix, everything seemed to work fine, until using the @ codebase context provider causes the extension host to crash.
> 
> Had you seen the same issue or have any ideas? [microsoft/vscode#88386](https://github.com/microsoft/vscode/issues/88386) seems like the most closely related issue, though seemed to have been solved

I was having the same issue while testing on this `worker_thread` but terminating the  worker thread `worker.terminate();` seems to fix that.

>until using the @ codebase context provider causes the extension host to crash.

I can think of one issue probably using @ codebase opening too many worker threads before terminating previous theard crasing, or probably adding some smart [resourse limit](https://nodejs.org/api/worker_threads.html#workerresourcelimits_1)

**Comment by sestinj** [comment]
@Iamshankhadeep the worker limit is a good idea. When you had the same problem, was it in debug mode, or was this with a packaged version of the extension? I would be curious whether you end up seeing the same problem that I did after running `cd extensions/vscode && node scripts/package.js` and then installing `build/continue-patch.vsix`

**Comment by Iamshankhadeep** [comment]
> @Iamshankhadeep the worker limit is a good idea. When you had the same problem, was it in debug mode, or was this with a packaged version of the extension? I would be curious whether you end up seeing the same problem that I did after running `cd extensions/vscode && node scripts/package.js` and then installing `build/continue-patch.vsix`

let me try that and I'll let you know 🔥

**Comment by sestinj** [comment]
Hey @Iamshankhadeep, I'm going to close this PR because even though you did everything that I expected to work, it seems that worker threads don't play nicely with VS Code. We'll still have this here for reference if we decide to look into it again, so I'm sure it will still be of use

**Pull request closed without merging**
