### PR TITLE
Add Flutter and Dart to pre-indexed docs

### PR DESCRIPTION
**Pull request by CaseyHillers**
## Description

Pre-index docs for Flutter and Dart

## Checklist

- [X] The relevant docs, if any, have been updated or created

## Screenshots

N/A

## Testing

I was able to run my local patch, but I'm not sure if anything else is needed to verify the change.

### CODE REVIEW

**Comment by RomneyDa** [comment]
would need to add preindexed embeddings to s3 before merging

@sestinj

**Comment by sestinj** [comment]
I am pretty confident it's more than widely-used enough to include here

**Comment by sestinj** [comment]
But yeah I'll make sure to do the indexing run before this is released

Thanks @CaseyHillers for the contribution!

**Comment by sestinj** [comment]
Hi @CaseyHillers, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Pull request merged**
