### PR TITLE
Use esbuild onEnd callback

### PR DESCRIPTION
**Pull request by RomneyDa**
Problem was that esbuild.context doesn't wait for build to finish, so activate extension was failing because extension host task was launched before build was complete

Now it won't think the task is complete before the build has finished

Credit @ ray strode [halfline] on discord!

### CODE REVIEW

**Comment by RomneyDa** [comment]
@ray strode [halfline]
https://discord.com/channels/1108621136150929458/1108621136830398496/1315729225126510707

**Comment by halfline** [comment]
so trying this, it doesn't actually fix the problem. I think the issue is if the `vscode-extension:esbuild` task is running in the background from a previous invocation, vscode isn't going to start it again even if it's called for (since it's already running).  So if you have `vscode-extension:esbuild` generate extensions.js then have `vscode-extension:continue-ui:build` call `prepackage.js` which removes extensions.js, calling `vscode-extension:esbuild` again later is going to be a noop, I think, and not regenerate the file (since it's still running in the background)

**Comment by halfline** [comment]
i posted https://github.com/continuedev/continue/pull/3276 to address this I think.

**Comment by RomneyDa** [comment]
@halfline the `onEnd` callback pretty black-and-white solved _first_ launch activation for me, I think we might have been solving two different problems - yours solves restarts, mine solves premature endPattern triggers. Or can you re-iterate which problem it didn't solve? Thanks for the contribution

**Comment by halfline** [comment]
oh if it solves a real problem ignore me

**Pull request merged**
