### PR TITLE
fix(gui): chat window scrollbar configurable visibility 

### PR DESCRIPTION
**Pull request by priyashpatil**
## Description

Fixes missing scrollbar
Closes: #2063 

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

### CODE REVIEW

**Comment by sestinj** [comment]
After talking this one over we don't want to bring back the scrollbar, at least in this form. The real estate of the sidebar is so small that even a little distraction can be a huge deal. I do understand that for accessibility purposes and certain workflows, the scrollbar can have value, so we may consider making this a config option, or trying to implement a less invasive scrollbar, or both. The former idea would mean putting it in the `ui` section of config.json

**Comment by priyashpatil** [comment]
> After talking this one over we don't want to bring back the scrollbar, at least in this form. The real estate of the sidebar is so small that even a little distraction can be a huge deal. I do understand that for accessibility purposes and certain workflows, the scrollbar can have value, so we may consider making this a config option, or trying to implement a less invasive scrollbar, or both. The former idea would mean putting it in the `ui` section of config.json

Made some changes to add custom scrollbar:

https://github.com/user-attachments/assets/6f9e2722-a3ae-4552-b1f2-39858bdaccf8

**Comment by priyashpatil** [comment]
Hey @Patrick-Erichsen, I've made some changes. Now instead of using custom scrollbar it uses native thin scrollbar. Along with this there's a config option that allows to toggle the scrollbar visibility.

```json
{
    "showChatScrollbar": true,
}
```

By default the scrollbar is hidden.

**Comment by sestinj** [comment]
Thanks Priyash!

**Comment by sestinj** [comment]
Hi @priyashpatil, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by priyashpatil** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
