### PR TITLE
refactor : declare and initialize class property

### PR DESCRIPTION
**Pull request by DongjaJ**
## Description

[ What changed? Feel free to be brief. ]

Typescript class grammar allows the constructor to declare and initialize properties at the same time.

I applied it to continue in this PR

And I want to ask you one thing.

If you look at the second commit of this PR, there are properties that have public access designators. Shouldn't these properties be designated as private access designators?

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [ ] The relevant docs, if any, have been updated or created

## Screenshots

[ For visual changes, include screenshots. ]

## Testing

[ For new or modified features, provide step-by-step testing instructions to validate the intended behavior of the change. ]

### CODE REVIEW

**Comment by sestinj** [comment]
This is great! Yes, it looks like those public properties in the second commit should all be private

**Comment by DongjaJ** [comment]
I modified the access designator from public to private

**Comment by Patrick-Erichsen** [comment]
Great work @DongjaJ !

**Comment by sestinj** [comment]
Hi @DongjaJ, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by DongjaJ** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
