### PR TITLE
Add github action to install dependencies

### PR DESCRIPTION
**Pull request by djgould**
## Description
I noticed some issues running the install script again, so figured this could be useful. At the very least for me to check if it happens in a clean env.

I only see one other github action in the project so let me know if there isn't any interest in adding more.

## Checklist

- [x] The base branch of this PR is `preview`, rather than `main`

### CODE REVIEW

**Comment by djgould** [comment]
Ah just realized I need approval for the workflow to run. You can see the current install failure in my fork. happens locally as well.

https://github.com/djgould/continue/actions/runs/9021010813/job/24787377254

**Comment by sestinj** [comment]
Hm yeah the approval is something we'll keep around for security reasons. Given this, I'm not sure it's super helpful to have the action here in the repo. Thoughts on a script instead to "remove-all-dependencies"? I don't disagree that the fresh start would be nice, and maybe we can just make it easy to do so locally. The other option is a local clone

**Comment by sestinj** [comment]
As for the issue, it seems like a matter of explicitly declaring the dependency? My plan was to move to pnpm anyway, so in the process of doing that I'm sure we'll solve this

**Comment by djgould** [comment]
> Given this, I'm not sure it's super helpful to have the action here in the repo

cool i'll close this then

> Thoughts on a script instead to "remove-all-dependencies"

That would be great!

>As for the issue, it seems like a matter of explicitly declaring the dependency? My plan was to move to pnpm anyway, so in the process of doing that I'm sure we'll solve this

Yeah I think it was just a missing dependency. Not sure how it slipped in. +1 for switching to pnpm

**Comment by sestinj** [comment]
totally! commit incoming for the switch to pnpm

**Pull request closed without merging**
