### PR TITLE
Add Flowise Provider

### PR DESCRIPTION
**Pull request by eduardocalixtokorp**
This is the implementation for [Flowise](https://flowiseai.com/) Provider.
I've followed the [contributing guidelines](https://github.com/continuedev/continue/blob/preview/CONTRIBUTING.md#adding-models).

Flowise has both [API](https://docs.flowiseai.com/using-flowise/api) and [Streaming](https://docs.flowiseai.com/using-flowise/streaming), so I've added a `requestMode` option to its schema.

### CODE REVIEW

**Comment by sestinj** [comment]
@eduardocalixtokorp Thanks for doing this so quickly, it looks very complete. Just a couple of questions:

Are there cases where the non-streaming API is necessary? If not it would be nice to remove the need for this option.

Does Flowise use a particular model? I noticed you added a new template type for it, but I previously thought Flowise was just an API that would let you use any model. Is it true that all API calls to Flowise are expected to have this template type?

**Comment by eduardocalixtokorp** [comment]
> @eduardocalixtokorp Thanks for doing this so quickly, it looks very complete. Just a couple of questions:
> 
> Are there cases where the non-streaming API is necessary? If not it would be nice to remove the need for this option.
> 
> Does Flowise use a particular model? I noticed you added a new template type for it, but I previously thought Flowise was just an API that would let you use any model. Is it true that all API calls to Flowise are expected to have this template type?

Hi @sestinj, thank you for the response. Regarding the non-streaming API, it is not necessary, but I thought it would be a great addition. Anyway, I'll remove it soon. Furthermore, you are also correct that Flowise does not need a template type, so I'll correct that too.

**Comment by sestinj** [comment]
@eduardocalixtokorp This all looks good to me! Thanks for making those few changes. I'm ready to merge this if you wouldn't mind making one tiny change: can you change the base branch to "preview"? We use this so that all changes go through our pre-release first

**Comment by eduardocalixtokorp** [comment]
> @eduardocalixtokorp This all looks good to me! Thanks for making those few changes. I'm ready to merge this if you wouldn't mind making one tiny change: can you change the base branch to "preview"? We use this so that all changes go through our pre-release first


Alright then, I'll fix that today because it seems that only changing the destination branch has caused some unwanted changes.

**Comment by eduardocalixtokorp** [comment]
Consider it done. I had to rewrite branch history due to some merge commits

**Comment by sestinj** [comment]
Thanks for doing that! I've added a note to CONTRIBUTING.md to hopefully avoid this in the future. Once again appreciate the good work here and you can look for the changes to be live in VS Code pre-release later today

**Comment by sestinj** [comment]
Hi @eduardocalixtokorp, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Pull request merged**
