### PR TITLE
Fix: Check for MCP Available Attributes

### PR DESCRIPTION
**Pull request by ajshedivy**
## Description

proposed fix for #3225 

### Solution
Since some servers do not provider resources, tools, etc., check if client methods are available with simple wrapper:
```typescript
this.client.listResources()
this.client.listTools()
this.client.listPrompts()
```

```typescript
  async checkClientAttribute(func: () => Promise<any>): Promise<any> {
    try {
      const result = await func();
      return result;
    } catch (e) {
      return null;
    }
  }

```

There is prob a better way to handle this, but it's a good hot fix 😁 

## Checklist

- [] The relevant docs, if any, have been updated or created

## Screenshots

image

## Testing

1. Install the filesystem server:

```bash
npm install -g @modelcontextprotocol/server-filesystem
```

2. Configure MCP in ~/.continue/config.json:

```json
{
  "experimental": {
    "modelContextProtocolServer": {
      "transport": {
        "type": "stdio",
        "command": "npx",
        "args": [
          "-y",
          "@modelcontextprotocol/server-filesystem",
          "/path/to/directory"
        ]
      }
    }
  }
}
```

## TODO

- [ ] **handle duplicate Tools**:
 Adding the `@modelcontextprotocol/server-filesystem` server produces the following warning with the default tools:

```bash
Warning: Encountered two children with the same key, `read_file`. 
Keys should be unique so that components maintain their identity across updates. 
Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

### CODE REVIEW

**Comment by ajshedivy** [comment]
To handle duplicate tools, an easy fix would just be to encode the BuiltinTools using some sort of prefix:
```typescript
export enum BuiltInToolNames {
  ReadFile = "builtin:read_file",
  ReadCurrentlyOpenFile = "builtin:read_currently_open_file",
  CreateNewFile = "builtin:create_new_file",
  RunTerminalCommand = "builtin:run_terminal_command",
  ViewSubdirectory = "builtin:view_subdirectory",
  ViewRepoMap = "builtin:view_repo_map",
  ExactSearch = "builtin:exact_search",
  SearchWeb = "builtin:search_web",
  ViewDiff = "builtin:view_diff",
}
```

**Comment by ajshedivy** [comment]
@sestinj @Patrick-Erichsen This is ready for review!

**Comment by SimonB97** [comment]
I tried to get this to work on my end, could you confirm my `config.json` structure please? I put "experimental" conf at the root (and at the end).

```json
{
  "models": [
    {
      "title": "Claude 3.5 Sonnet (Free Trial)",
      "provider": "free-trial",
      "model": "claude-3-5-sonnet-latest",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses."
    },
    {
      "title": "GPT-4o (Free Trial)",
      "provider": "free-trial",
      "model": "gpt-4o",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses."
    },
    {
      "title": "Llama3.1 70b (Free Trial)",
      "provider": "free-trial",
      "model": "llama3.1-70b",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses."
    },
    {
      "title": "Codestral (Free Trial)",
      "provider": "free-trial",
      "model": "codestral-latest",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses."
    },
    {
      "model": "claude-3-5-sonnet-latest",
      "provider": "anthropic",
      "apiKey": "",
      "title": "Claude 3.5 Sonnet"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete",
    "provider": "free-trial",
    "model": "codestral-latest"
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "experimental": {
    "modelContextProtocolServer": {
      "transport": {
        "type": "stdio",
        "command": "npx",
        "args": [
          "-y",
          "@modelcontextprotocol/server-filesystem",
          "~/Desktop"
        ]
      }
    }
  },
  "embeddingsProvider": {
    "provider": "free-trial"
  },
  "reranker": {
    "name": "free-trial"
  }
}
```

**Comment by Patrick-Erichsen** [comment]
@adamszewe thanks for opening this!

 I poked around the TS interface for `client` a bit and I think we can use `client.getServerCapabilities` in the `modifyConfig` to do this a bit cleaner.

https://github.com/search?q=repo%3Amodelcontextprotocol%2Ftypescript-sdk%20getServerCapabilities&type=code

```ts
--
150 | * After initialization has completed, this will be populated with the server's reported capabilities.
151 | */
152 | getServerCapabilities(): ServerCapabilities \| undefined {
153 | return this._serverCapabilities;
154 | }


// Server supports resources and tools, but not prompts
--
214 | expect(client.getServerCapabilities()).toEqual({
215 | resources: {},
216 | tools: {},
217 | });
```

I think our logic could then look something like this:

```ts
    const capabilities = this.client.getServerCapabilities()

    if (capabilities?.resources) {
      const resources = this.client.listResources()
      // ...
    }
```


+1 to the implementation for `BuiltInToolNames`, I think the prefix is a good call.

**Review by sestinj — CHANGES_REQUESTED** [review]
@ajshedivy I think the right way to do this is probably with the `client.getServerCapabilities()` method on the MCP client. Any interest in attempting that?

**Review by sestinj — APPROVED** [review]

**Comment by YanxingLiu** [comment]
> I tried to get this to work on my end, could you confirm my `config.json` structure please? I put "experimental" conf at the root (and at the end).
> 
> ```json
> {
>   "models": [
>     {
>       "title": "Claude 3.5 Sonnet (Free Trial)",
>       "provider": "free-trial",
>       "model": "claude-3-5-sonnet-latest",
>       "systemMessage": "You are an expert software developer. You give helpful and concise responses."
>     },
>     {
>       "title": "GPT-4o (Free Trial)",
>       "provider": "free-trial",
>       "model": "gpt-4o",
>       "systemMessage": "You are an expert software developer. You give helpful and concise responses."
>     },
>     {
>       "title": "Llama3.1 70b (Free Trial)",
>       "provider": "free-trial",
>       "model": "llama3.1-70b",
>       "systemMessage": "You are an expert software developer. You give helpful and concise responses."
>     },
>     {
>       "title": "Codestral (Free Trial)",
>       "provider": "free-trial",
>       "model": "codestral-latest",
>       "systemMessage": "You are an expert software developer. You give helpful and concise responses."
>     },
>     {
>       "model": "claude-3-5-sonnet-latest",
>       "provider": "anthropic",
>       "apiKey": "",
>       "title": "Claude 3.5 Sonnet"
>     }
>   ],
>   "tabAutocompleteModel": {
>     "title": "Tab Autocomplete",
>     "provider": "free-trial",
>     "model": "codestral-latest"
>   },
>   "customCommands": [
>     {
>       "name": "test",
>       "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
>       "description": "Write unit tests for highlighted code"
>     }
>   ],
>   "contextProviders": [
>     {
>       "name": "code",
>       "params": {}
>     },
>     {
>       "name": "docs",
>       "params": {}
>     },
>     {
>       "name": "diff",
>       "params": {}
>     },
>     {
>       "name": "terminal",
>       "params": {}
>     },
>     {
>       "name": "problems",
>       "params": {}
>     },
>     {
>       "name": "folder",
>       "params": {}
>     },
>     {
>       "name": "codebase",
>       "params": {}
>     }
>   ],
>   "slashCommands": [
>     {
>       "name": "share",
>       "description": "Export the current chat session to markdown"
>     },
>     {
>       "name": "cmd",
>       "description": "Generate a shell command"
>     },
>     {
>       "name": "commit",
>       "description": "Generate a git commit message"
>     }
>   ],
>   "experimental": {
>     "modelContextProtocolServer": {
>       "transport": {
>         "type": "stdio",
>         "command": "npx",
>         "args": [
>           "-y",
>           "@modelcontextprotocol/server-filesystem",
>           "~/Desktop"
>         ]
>       }
>     }
>   },
>   "embeddingsProvider": {
>     "provider": "free-trial"
>   },
>   "reranker": {
>     "name": "free-trial"
>   }
> }
> ```

Hello, have you solved the problem. I encountered the same issue that I have added the modelContextProtocolServers, but I cannnot see the mcp after I typed @.

**Comment by SimonB97** [comment]
Tried last time a few days ago (maybe they have updated it since) but sadly still didn't work for me

**Comment by ajshedivy** [comment]
@SimonB97 @YanxingLiu the config has actually changed in the recent pre-release:
change `modelContextProtocolServer` -> `modelContextProtocolServers` (severs in now plural). I opened a PR with some potential fixes for multiple servers: #3462

**Comment by YanxingLiu** [comment]
> Contributor

Thanks for your work, I have tried the setting mentioned in https://github.com/continuedev/continue/pull/3462. But it still failed. The detail is shown in that PR. I would like to ask if you know why this is. Thanks a lot for your help.

**Pull request merged**
