### PR TITLE
vscode: Make esbuild-watch script fire when extension.js disappears

### PR DESCRIPTION
**Pull request by halfline**
When running the VS Code extension, the prepackage script cleans the output directory in preparation for it to get populated with new content:

    // Clear folders that will be packaged to ensure clean slate
    ...
    rimrafSync(path.join(__dirname, "..", "out"));
    fs.mkdirSync(path.join(__dirname, "..", "out", "node_modules"), {
      recursive: true,
    });

That, unfortunately, means extension.js can get blown away after it's been built, leading to an error message when launching the test environment:

  Activating extension 'Continue.continue' failed: Cannot find module
  '.../extensions/vscode/out/extension.js'

As part of the build pipeline, there is a esbuild-watch script that watches for changes to the input source to rebuild extension.js when they change.

This commit addresses the above problem by leveraging the esbuild-watch script to also rebuild extension.js when it disappears.

### CODE REVIEW

**Comment by RomneyDa** [comment]
Linking related PR here
https://github.com/continuedev/continue/pull/3268

found the specific build-completed callback

**Review by sestinj — APPROVED** [review]
this is great, thanks!

As Dallin mentioned in Discord, we're happy to accept either this PR with the updated changes, or go ahead and just merge the other, lmk!

**Comment by halfline** [comment]
let's close this one, because it's less root cause-y

**Comment by halfline** [comment]
So Dallin's fix wasn't right, I think.

I posted https://github.com/continuedev/continue/pull/3276 as an alternative, that's a little closer to the meat of the matter.

**Pull request closed without merging**
