### PR TITLE
Ensure don't go over sqlite max like pattern length

### PR DESCRIPTION
**Pull request by RomneyDa**
## Description

Truncate LIKE comparison pattern in autocomplete LRU cache

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

See discussion in 
https://github.com/continuedev/continue/issues/2688

### CODE REVIEW

**Comment by RomneyDa** [comment]
This is one way but maybe better, reevaluate how the prefix is constructed and why it would get so long:

https://github.com/continuedev/continue/blob/334705c0a3c4fd081c22faf13f9f5478a57600d4/core/autocomplete/completionProvider.ts#L536-L601

**Comment by sestinj** [comment]
@RomneyDa this is a good backup to have so thanks for doing it. And yes we should also re-evaluate, though I'd asked the person whether changing to smaller contextLength/maxPrefixTokens solves it, as this is a likely explanation.

One thing to change on this PR before we merge: the LIKE pattern (at least the autocomplete one) should be truncated from the front first. Right now we'll leave out chars at the end, but if it's too long we should be leaving out tokens at the start

**Comment by RomneyDa** [comment]
@sestinj updated

**Comment by sestinj** [comment]
@RomneyDa thanks this is great. I made a small change myself because it was super minimal and biased to just getting this merged, but I threw in a few (Continue-generated) tests to show examples of what was intended here

**Pull request merged**
