### PR TITLE
add zh-CN docs

### PR DESCRIPTION
**Pull request by mayf09**
based on 2263812

### CODE REVIEW

**Comment by mayf09** [comment]
Hi, @sestinj, I add a new version of zh-CN docs.

**Comment by sestinj** [comment]
Cool!! I will take a look. Thanks so much for doing this : )

**Comment by sestinj** [comment]
@mayf09 For some reason all of the /zh-CN pages are redirecting right back to /, any ideas on how to fix this?

**Comment by mayf09** [comment]
> @mayf09 For some reason all of the /zh-CN pages are redirecting right back to /, any ideas on how to fix this?

@sestinj How do you build docs? I use follow command, and it's looks good.

in `continue/docs` folder,
```
npm run build
npm run serve
```

**Comment by sestinj** [comment]
You're right, this works for me, thanks!

I switched to zh-CN, then had my browser auto-translate back to English and all of the pages look good 👍

@mayf09 What do you think about maintaining this going forward? Is there a tool you've used that makes it easy, and would you be willing to occasionally update things when they change?

and finally cc @TyDunn for any general thoughts

**Comment by mayf09** [comment]
I will follow up this project, update docs occasionally, maybe once a month.
Currently, there is no such tool, just by hand.

**Comment by sestinj** [comment]
amazing, well I really appreciate this contribution! Merging now and looking forward to working together more!

**Pull request merged**
