### PR TITLE
[CON-245] Add docs through config.json

### LINKED ISSUE #1442: [CON-245] Add docs through config.json
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Can't currently specify docs sites to index through config.json

### Solution

Ideally, users can write this in their config.json:

```json
"contextProviders": [{
  "name": "docs",
  "params": { "sites": [
    {
      "title": "Jinja",
      "startUrl": "https://jinja.palletsprojects.com/en/3.1.x/",
      "rootUrl": "https://jinja.palletsprojects.com/en/3.1.x/",
    },
    {
      "title": "React",
      "startUrl": "https://react.dev/reference/",
      "rootUrl": "https://react.dev/reference/",
    }
  ]}
}]
```

<sub>[CON-245](https://linear.app/continue/issue/CON-245/add-docs-through-configjson)</sub>

### PR DESCRIPTION
**Pull request by priyashpatil**
## Description

- [x] Add showing docs submenu from config
- [x] Fix docs indexing progress calculator
- [x] Avoid showing duplicate docs in submenu
- [x] Add indexing commands to manual trigger
- [x] Add auto indexing with debounce (If disableIndexing options is false).

**Note**: This PR do not show the indexing progress in UI due to possible collision with progress updates with Code Indexing. This will be resolved in a separate PR.

Closes #1442 

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

### CODE REVIEW

**Comment by sestinj** [comment]
@priyashpatil I'm very sorry but due to a rebase we had to make it seems like this PR has been really muddled. Is there any way you could open a new one on the dev branch, or share a local diff patch that I could try to apply manually?

I tried to get all PRs through before the rebase but didn't merge this one because it was still in draft

**Comment by priyashpatil** [comment]
> @priyashpatil I'm very sorry but due to a rebase we had to make it seems like this PR has been really muddled. Is there any way you could open a new one on the dev branch, or share a local diff patch that I could try to apply manually?
> 
> I tried to get all PRs through before the rebase but didn't merge this one because it was still in draft

this is still in draft state it's not complete

**Comment by Patrick-Erichsen** [comment]
Hi @priyashpatil , apologies for the slow review.

Thanks for the contribution! This is a great addition. Only point of feedback is that @sestinj and I are a little concerned that if users have to manually run an indexing command, they might forget to do so.

Nate recently consolidated the docs logic into a single class here: https://github.com/continuedev/continue/blob/dev/core/indexing/docs/DocsService.ts#L29

I think if we added a debounce, e.g. for "scenarios where users might have auto-save enabled", we can avoid constantly indexing without introducing an additional action for the user to take.

**Comment by priyashpatil** [comment]
> Hi @priyashpatil , apologies for the slow review.
> 
> Thanks for the contribution! This is a great addition. Only point of feedback is that @sestinj and I are a little concerned that if users have to manually run an indexing command, they might forget to do so.
> 
> Nate recently consolidated the docs logic into a single class here: https://github.com/continuedev/continue/blob/dev/core/indexing/docs/DocsService.ts#L29
> 
> I think if we added a debounce, e.g. for "scenarios where users might have auto-save enabled", we can avoid constantly indexing without introducing an additional action for the user to take.

Okay. Will add debounce then.

**Comment by priyashpatil** [comment]
@Patrick-Erichsen Added auto indexing with debounce and some config checks.

**Comment by Patrick-Erichsen** [comment]
Thanks for your patience on getting this merged @priyashpatil , great work! This turned out really nicely.

**Pull request merged**
