### PR TITLE
feat: convert issue templates to issue form templates

### PR DESCRIPTION
**Pull request by LangLangBart**
#### proposal

- Convert the `Markdown` issue templates to issue template forms written in `YAML`.
- The main goal is to save time for the maintainer by ensuring all necessary
  information is provided, thereby reducing the need for follow-ups. Additionally, the
  user is required to confirm that they have already consulted the troubleshooting page or
  searched for similar issues.

#### links
- [Github Docs - Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

### todo
- [x] check if this is desired by the maintainers of `continuedev/continue`
  - [ ] check wording
  - [ ] check links, for example to the troubleshooting page or discord
  - [ ] update `bug-report` link in `continue/docs/docs/troubleshooting.md`
  - [ ] update `feature-request` link in `continue/docs/docs/customization/context-providers.md`
  - [ ] test it, demo repo: https://github.com/LangLangBart/yaml
    - the repo is up to date with this patch

### CODE REVIEW

**Comment by sestinj** [comment]
This looks quite nice! I think it's okay not to require _all_ of the fields, just so that there is a super low friction path if somebody wants it, but otherwise this is great. I'll do a full run-through on the wording soon

**Comment by LangLangBart** [comment]
> I think it's okay not to require all of the fields, just so that there is a super low friction path if somebody wants it. 
Ok, I set it to false, including the check boxes. 
Put the required environment information in a single Markdown field instead of multiple checkboxes.

**Comment by sestinj** [comment]
Awesome. Sharing this with Ty as well for some wording feedback, then I think it'll be totally good to go

**Review by TyDunn — APPROVED** [review]
@LangLangBart This is awesome! Great work. Super excited to get this merged in

**Pull request merged**
