### PR TITLE
Add initial support to NVIDIA NIMs model provider

### PR DESCRIPTION
**Pull request by adawalli**
## Description

Add initial support for NVIDIA NIMs. Although NIMs are OpenAI API compatible, there are some design decisions that need to be accommodated outside the OpenAI base LLM class.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Testing

[ For new or modified features, provide testing instructions. ]

### CODE REVIEW

**Comment by adawalli** [comment]
@sestinj - I think we are ready for a basic onboarding of NIM's - the major thing is that we accommodate the limited number of stops on starcoder2

**Comment by shivay-at-pieces** [comment]
@adawalli is this a PR to get support for LLM option with Nvidia?

**Comment by adawalli** [comment]
> @adawalli is this a PR to get support for LLM option with Nvidia?

Yes, that's right. NVIDIA NIMs do implement OpenAI API for model usage, but there are some oddities that we need to account for

**Review by sestinj — APPROVED** [review]
Perfect!

**Pull request merged**
