### PR TITLE
Draft fixing @url and introducing default urls that you reference often

### PR DESCRIPTION
**Pull request by bra1nDump**
#370 

Correct completions appear
image

Not prioritized, but when hit enter it works at least
image

### CODE REVIEW

**Comment by sestinj** [comment]
@bra1nDump This is past draft stage imo unless we want to add prioritization to this PR

**Comment by bra1nDump** [comment]
@sestinj yep it's good to go, I was thinking to add prioritization at first, but that should be separate

**Comment by sestinj** [comment]
@bra1nDump fyi I made a fix to prioritization [here](https://github.com/continuedev/continue/commit/5590f63e42fda38d780bdc390361a65b65576498#diff-eadabb6825550b452645200fee075a9edd2f5e8a8553201ce53936d96fd57d8dR179)

**Comment by bra1nDump** [comment]
@sestinj I assume it's update_ranking_rules? I will play around with it Monday. Don't really know meilisearch api. I was imagining hard filtering by prefix such as @url and other @things, so not just the ordering

**Comment by sestinj** [comment]
Ranking first by attribute match happened to have the desired effect because it matches first for the title

**Comment by sestinj** [comment]
Hi @bra1nDump, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by bra1nDump** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
