### PR TITLE
Query vLLM OpenAI /models endpoint to get model name and context window

### PR DESCRIPTION
**Pull request by simon376**
## Description

Similar to #755 , the OpenAI-compatible API server by vLLM exposes both the model name via `id` and the context length via `max_model_len`, which can be used to automatically setup the context length of the deployed LLM.

I'm not sure how to best check if the endpoint should be queried, e.g. by checking the API Base URL, or introducing a new apiType besides Azure, etc.

## Checklist

- [x ] The base branch of this PR is `dev`, rather than `main` **it's preview as in your contributing guidelines**
- [ ] The relevant docs, if any, have been updated or created

## References

- [vLLM PR](https://github.com/vllm-project/vllm/pull/4643) adding `max_model_len`
- #609 Looks like this is closely related to the "AUTODETECT" functionality. however, that only uses the model names, not additional parameters as far as I am aware of (ref. `load.ts:244`). So it may be better to adjust the `listModels()` interface to include model parameters in its response

### CODE REVIEW

**Comment by simon376** [comment]
sorry I messed something up, I only intended to include my one change in the OpenAI.ts file

**Comment by sestinj** [comment]
@simon376 I think this might be a good enough reason to make a subclass of the OpenAI class (we do this with Deepseek, Groq, and others for example). Everything can be the same except that there doesn't need to be a URL check to find out whether it is an instance of vLLM

**Comment by Patrick-Erichsen** [comment]
Hey @simon376 , any progress on this? Would love to get it shipped!

**Comment by simon376** [comment]
@sestinj  I've created a new vLLM subclass and add documentation for it. Sorry for the whitespace changes in OpenAI.ts, couldn't figure out how to get rid of them

**Comment by sestinj** [comment]
Great, now worries on the whitespace this looks perfect

**Review by sestinj — APPROVED** [review]

**Comment by agatapog** [comment]
Hi @sestinj what version of the extension has this feature been integrated into?

**Comment by sestinj** [comment]
Hi @simon376, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by simon376** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
