### PR TITLE
✨ add Cohere as Reranker

### LINKED ISSUE #1122: Support Cohere as Reranker
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

[Codebase retrieval](https://continue.dev/docs/walkthroughs/codebase-embeddings) could use Cohere's [Rerank](https://docs.cohere.com/docs/reranking) models

### Solution

Add supporting code under [core/context/rerankers](https://github.com/continuedev/continue/tree/d40b4c5d4bf593bc81f0b909ccae9837e8785bfb/core/context/rerankers)

### PR DESCRIPTION
**Pull request by maxbrunet**
## Description

Closes #1122

## Checklist

- [x] The base branch of this PR is `preview`, rather than `main`

### CODE REVIEW

**Comment by sestinj** [comment]
@maxbrunet flawless, thank you for the PR!

Related to this, I'm curious whether you're aware of any good re-ranking benchmarks outside of those from MTEB, particularly if they are specific to code?

**Review by sestinj — APPROVED** [review]

**Comment by maxbrunet** [comment]
Thank you @sestinj, would you have an idea when we can expect these features to be released?

> Related to this, I'm curious whether you're aware of any good re-ranking benchmarks outside of those from MTEB, particularly if they are specific to code?

I asked [Coral, our showcase chatbot](https://cohere.com/chat), and it literally pointed me to one of your blog posts, so I might not bring much news to you unfortunately: https://blog.continue.dev/an-introduction-to-code-llm-benchmarks-for-software-engineers/

By asking around, Human Eval, MBPP, DS1000 were mentioned to me, and these 2 projects not in the blog post:

* https://github.com/github/CodeSearchNet
* https://github.com/Jun-jie-Huang/CoCLR

**Comment by sestinj** [comment]
@maxbrunet I just now am pushing a pre-release version (0.9.119) including all of the updates.

Hilarious that it brought back our post... The links you shared are new to me though, thank you!

**Comment by sestinj** [comment]
Sorry misspoke on releasing yesterday. Working on a fix that had to happen before, then ideally today will be out

**Comment by maxbrunet** [comment]
No worries, would it possible to have matching Git tags on the commits used to build them too? I had not realized there were versions published without Git tag

Also what about JetBrains?

**Comment by sestinj** [comment]
@maxbrunet JetBrains doesn't yet have support for codebase retrieval, but this isn't far off, just a small refactor I want to get in beforehand.

It's true that pre-releases don't get tagged or added to GitHub releases. The plan is to only tag main releases because pre-release happens so much more frequently (unless there's a really strong reason why this should be considered)

**Comment by maxbrunet** [comment]
> JetBrains doesn't yet have support for codebase retrieval

Ok, that's fine, no hurry, beyond cobase retrieval, I was also wondering if Cohere as model provider was released there

> The plan is to only tag main releases because pre-release happens so much more frequently (unless there's a really strong reason why this should be considered)

Git tags are cheap and make it easy to identify if a commit is part of a release, e.g.

image

It also makes it straightforward to bisect between two releases if something breaks

**Comment by sestinj** [comment]
That's a fair enough point about bisecting. Seems reasonable enough for us to start tagging pre-releases then

I'm working on getting JetBrains 0.0.46 out the door right now, but the store will probably accept it on Monday morning. This will include the Cohere model provider

**Pull request merged**
