### PR TITLE
Update webviewView

### PR DESCRIPTION
**Pull request by viciousstar**
## Description

[ What changed? Feel free to be brief. ]

## Checklist

- [ x ] The base branch of this PR is `dev`, rather than `main`
- [ x ] The relevant docs, if any, have been updated or created

## Screenshots

[ For visual changes, include screenshots. ]

## Testing

[ For new or modified features, provide step-by-step testing instructions to validate the intended behavior of the change. ]

### CODE REVIEW

**Comment by sestinj** [comment]
@viciousstar What was the exact problem that this solved? This seems to make sense, but I want to do a bit of testing and it would help to know the issue you intended to fix

**Comment by viciousstar** [comment]
> @viciousstar What was the exact problem that this solved? This seems to make sense, but I want to do a bit of testing and it would help to know the issue you intended to fix

problem is func isVisible return undifined，though the func is not called anywhere now.
```
  get isVisible() {
    return this._webviewView?.visible;
  }
```

**Comment by Patrick-Erichsen** [comment]
@viciousstar is there any bugs this was causing that you can walk us through, i.e. how did the issue come to your attention?

**Comment by viciousstar** [comment]
> @viciousstar is there any bugs this was causing that you can walk us through, i.e. how did the issue come to your attention?

No, I haven't found any bugs. I was trying to provide a command for the extension to close the webview when it's visible, which invokes the isVisible function, and I found that isVisible returned undefined.

**Review by sestinj — APPROVED** [review]

**Pull request merged**
