### PR TITLE
feat: add Vertex AI support

### PR DESCRIPTION
**Pull request by reosablo**
## Description

related to #1573

Adds supports for models on Vertex AI.

Three new model providers have been implemented:

- `gemini-vertexai` (for Gemini 1.5 Pro, etc.)
- `anthropic-vertexai` (for Claude 3.5 Sonnet, etc.)
- `mistral-vertexai` (for Mistral Large, Codestral, etc.)

These providers closely resemble the existing `gemini`, `anthropic`, and `mistral` providers.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Screenshots

feature-vertexai

## Testing

I've tested this PR in VSCode debugging and confirmed that both chat and auto-completion function as expected.

### CODE REVIEW

**Review by sestinj — APPROVED** [review]
Nice work!

**Review by Thompson1985 — APPROVED** [review]

**Comment by Lash-L** [comment]
Hey @reosablo thanks for doing this.

I've been spending some time setting up text-embedding-004 and code-gecko.

It has kind of been making me think, from a ui perspective, do you think it makes more sense to have all of vertexai under one provider?

And then inside _streamChat and all of the other functions, it handles correctly based off of the model name?

I have started doing the change, but I wanted to get a second opinion.

**Comment by ppsirius** [comment]
@reosablo you don't pass any credential so how I should authenticate with vertex?

**Comment by reosablo** [comment]
@Lash-L 
> do you think it makes more sense to have all of vertexai under one provider?

That sounds like a better idea. I actually tried implementing a similar approach with `OpenAIVertexAI` extending `OpenAI` for [Llama models](https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/llama), but ran into some challenges.

> Where do things like code-gecko live? What about Gemma? They aren't technically Gemini - do they need their entire own vertexai llm object? That feels a bit weird

I think that the current model providers seem to handle too many functionalities. Separating them into platform adapters and model adapters could be an effective solution. This could be a large refactoring.

**Comment by reosablo** [comment]
@ppsirius
Please make sure that the Google Application Default Credentials (ADC) are properly set up on your machine. You can verify this by running the command `gcloud auth print-access-token`. This should return an access token.

If you haven't already, you'll need to run `gcloud auth application-default login` to set up the ADC.

See: https://cloud.google.com/vertex-ai/docs/authentication

**Comment by ppsirius** [comment]
Thanks for explanation, I successfully login but got error :[
```json
[{
  "error": {
    "code": 429,
    "message": "Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: anthropic-claude-3-5-sonnet. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.",
    "status": "RESOURCE_EXHAUSTED"
  }
}
]
```

**Comment by sestinj** [comment]
Hi @reosablo, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by reosablo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
