### PR TITLE
Main

### PR DESCRIPTION
**Pull request by basedanarki**
## Description

- 3.5 sonnet now caches by default
- disposable "/nocache" /cache" for escalation or destruction after beta
- non-invasive implementation hoping for this to become industry standard and join main Types!

## Checklist

- [ x] The base branch of this PR is `dev`, rather than `main`
- [ x] The relevant docs, if any, have been updated or created

## Testing

It's a header, it fails unnoticeably or chatty users save a boatload of money.

### CODE REVIEW

**Comment by basedanarki** [comment]
A very real and exciting beta development from Anthropic lol disc guy was understandably confused talking about savings in caps ([read up on their new query caching here](https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#how-many-cache-breakpoints-can-i-use)). I was already down to chat with codebases as the speed is blinding with 3.5 Sonnet (idk TS lol look at the PR). This is over a 90% reduction in read costs so we can iterate massively.

image

**Comment by sestinj** [comment]
@basedanarki This is awesome! Few notes, but would love to get this merged:

- The dingboard addition is also great, but not something we can merge : )
- Can you make the PR against the `dev` branch rather than `main` so that this has the chance to be tested before GA?
- I think that it might make sense to control context caching on a per-model basis, and just include this in the `LLMOptions` type, alongside things like maxTokens, temperature, etc...

**Comment by Patrick-Erichsen** [comment]
Closing in favor of #2096 - unfortunately since this was opened to `main` we weren't able to patch the PR and get it merged.

**Comment by Patrick-Erichsen** [comment]
@basedanarki - heads up that we gave you a shoutout in a recent blogpost for the work here! https://blog.continue.dev/why-were-excited-about-prompt-caching-for-engineering-teams/

**Pull request closed without merging**
