### PR TITLE
fix!: change mistral api base

### PR DESCRIPTION
**Pull request by aretrace**
## Description

Change the Mistrial API base to the official endpoint, replacing old and nonworking codestral endpoint.

## Checklist

- [X] The base branch of this PR is `dev`, rather than `main`
- [X] The relevant docs, if any, have been updated or created

### CODE REVIEW

**Comment by sestinj** [comment]
@aretrace as far as I am aware Codestral is still available. Are you having trouble connecting?

**Comment by aretrace** [comment]
@sestinj, yes for `tabAutocompleteModel`, I changed `apiBase` per https://github.com/continuedev/continue/issues/1396#issuecomment-2142603194 and it worked (this is still using the Codestral model).
I don't think `"https://codestral.mistral.ai/v1/"` is available (I get a 404, not a 401 or 200).

**Comment by sestinj** [comment]
@aretrace I think the problem here comes from Mistral having separate API keys for Codestral and Mistral, where one key won't work with the other's API base. Until this changes, we wish to keep Codestral as the default because it is free for individuals to use

**Comment by aretrace** [comment]
@aretrace I see, would some disambiguation in the docs be welcomed regarding this?

**Comment by sestinj** [comment]
Definitely! We'd done so here (https://continue.dev/walkthroughs/set-up-codestral) but are also working on a docs rewrite where we'll make it even more clear (also in product onboarding)

**Pull request closed without merging**
