### PR TITLE
Add Doc Indexing Max Depth

### PR DESCRIPTION
**Pull request by justinmilner1**
## Description

Continue's add docs feature currently crawls pages until it runs out of links - this pr introduces a 'max depth' parameter which intends to prevent cases where indexing continues excessively.

Originated from [this](https://github.com/continuedev/continue/issues/1156) thread:
Screenshot from 2024-05-28 12-49-42

Screenshot from 2024-05-28 12-50-09

### Changes:
- New input box in the addDocs diagog
- Backend changes to indexing
   - stop crawling at maxDepth
   - catch errors where reasonable (ex: bad urls)
   - condense freely-defined object into SiteIndexingConfig object
   - make github page crawl use 'default' branch
   
### Testing:
Cases below passed

**UI:**
- try entering non-numerical
- try negative input
- try special characters

**Backend:**
- use default input 
     - confirm expected depth
     - confirm docs are indexed
- use custom input
    - confirm expected depth
    - confirm docs are indexed
- Use with wikipedia, maxDepth 1
    - should not index 'forever'

### CODE REVIEW

**Comment by sestinj** [comment]
Is it purposeful to remove the special crawler for GitHub pages? I haven't visited this in a while, so it very well could have looked better to remove that.

**Comment by justinmilner1** [comment]
@sestinj Ah, purposeful initially, but I intended to move it back before the pr. 

The special crawler is failing (socket hanging up, urls not being found). I haven't looked that deep into it yet - will do this and let you know.

**Comment by justinmilner1** [comment]
@sestinj Looks like the github crawler was only searching for a 'main' branch, so if 'main' didn't exist then it would fail. 
I've added a step to check for the default branch name, then use that.

**Review by sestinj — APPROVED** [review]

**Comment by sestinj** [comment]
Great work @justinmilner1!

**Pull request merged**
