### PR TITLE
Autodetect Docs V1

### PR DESCRIPTION
**Pull request by RomneyDa**
## Description

- Searches for package files in repo
- Parses packages from package files
- Collects docs links from registries
- Shows suggestions to user with relevant warnings, etc.
- Indexing is immediate and shows in peek on form
- Works for python and node currently

I should update the docs (the docs docs) before merging

## Checklist

- [ ] The relevant docs, if any, have been updated or created

## Screenshots

image

image

### CODE REVIEW

**Review by Patrick-Erichsen — APPROVED** [review]
Nice work!  Everything worked perfect for me out of the box. Just some UI nitpicks below, nothing that I think is preventing us from shipping so pick/choose what you think is worthwhile

- I think we can remove the "FileIcon". Lot of color, takes up horizontal space, and is potentially a bit confusing, e.g. a given package.json dep may or may not be also written in TS
- I think we should just use a lightgray `PlusIcon` for the leftmost "Add" action. The PlusCircleIcon is hard to read on small fonts in HeroIcons, and when it's the triangle it's unclear that you can still add it. Maybe warning goes alongside the URL somehow
- "Done" and "Go" are a bit confusing to me. Maybe "Go" becomes "Add", and "Done" becomes "Close"? It's also a bit unclear to me whether those buttons are supposed to be associated to the entire dialog, or just the form 
- Feels like the title/start url needs a title of some sort
Got this when I didn't have a package.json
Screenshot 2024-11-22 at 9 17 43 AM

I think the spinners are a bit noisy with multiple loaders. I'd lean towards just removing
Screenshot 2024-11-22 at 10 56 21 AM

"No docs link found" isn't legible on dark mode unless the row is hovered
Screenshot 2024-11-22 at 10 26 25 AM

We have the horizontal space, so I think we could turn this into an "+ Add doc" button to make this more prominent
Screenshot 2024-11-22 at 10 50 02 AM

**Comment by RomneyDa** [comment]
@Patrick-Erichsen agree with/implemented all those changes

image

image

**Comment by Patrick-Erichsen** [comment]
Beautiful! Can't approve on mobile I guess but LGTM 🫡

**Comment by RomneyDa** [comment]
Fixes https://github.com/continuedev/continue/issues/2715

**Pull request merged**
