### PR TITLE
Add support for phi2 model via Ollama

### PR DESCRIPTION
**Pull request by apawloski**
This adds support for Microsft's [phi-2](https://ollama.ai/library/phi) model via ollama. Thought this would be a simple first PR. If there are tests or docs that should be updated, I'm happy to do that but could use a pointer as to where.

### CODE REVIEW

**Comment by apawloski** [comment]
If you'd like me to use a different branch (preview maybe?) let me know.

**Comment by sestinj** [comment]
Thanks for doing this! Preview would be preferable, and the file to do that in then would be `core/llm/llms/Ollama.ts`.

There's a small, brand new section on adding new models to Continue [here](https://github.com/continuedev/continue/blob/preview/CONTRIBUTING.md#adding-models). To get autocompletion in config.json and some other things there are just a few more steps to follow. Would you have any interest in tackling some of these? If not, happy to do them myself after this is merged.

I might not add phi-2 to the UI, so you could skip the modelData.ts part

**Comment by morandalex** [comment]
waiting for the merge!

**Comment by apawloski** [comment]
Sorry, this got lost during my end of year holidays. I'm going to make the changes against preview in the new locations. When that's ready, will close this PR and open a new one.

**Comment by apawloski** [comment]
Closing this and moving work to https://github.com/continuedev/continue/pull/732

**Pull request closed without merging**
