### PR TITLE
add zh-CN docs

### PR DESCRIPTION
**Pull request by mayf09**
based on tag v0.0.39-jetbrains

### CODE REVIEW

**Comment by mayf09** [comment]
continue-docs-en
continue-docs-zh-CN

**Comment by sestinj** [comment]
@mayf09 Thank you for this great contribution! We would be very happy to have translated docs—my one concern is that we are planning to make a lot of improvements to the documentation in the next 1-2 weeks, and I want to be sure that the translation can remain up-to-date. Would you be interested in helping out again at that point, and occasionally afterward? This will have huge value, but only if it can stay close to fully-updated.

**Comment by mayf09** [comment]
> @mayf09 Thank you for this great contribution! We would be very happy to have translated docs—my one concern is that we are planning to make a lot of improvements to the documentation in the next 1-2 weeks, and I want to be sure that the translation can remain up-to-date. Would you be interested in helping out again at that point, and occasionally afterward? This will have huge value, but only if it can remain mostly updated.
Yes, I'm happy to translate those docs. Continue improves fast, this is very good.

**Comment by mayf09** [comment]
> @mayf09 Thank you for this great contribution! We would be very happy to have translated docs—my one concern is that we are planning to make a lot of improvements to the documentation in the next 1-2 weeks, and I want to be sure that the translation can remain up-to-date. Would you be interested in helping out again at that point, and occasionally afterward? This will have huge value, but only if it can remain mostly updated.

Yes, I'm happy to translate docs. Continue improves fast, this is very good.

**Comment by kaiqigong** [comment]
Great job! @mayf09,  any interest in supporting i18n in plugins?
Or is there an official plan to support i18n? @sestinj

**Comment by sestinj** [comment]
Hi @mayf09, I wanted to check back in on this now that we've gotten our docs into a better place. Before I was hesitant to merge because I knew it would require lots of continued maintenance and we had changes planned to the docs. Now we have completed a couple of rewrites. Is this still a project you're interested in taking on and maintaining?

**Comment by mayf09** [comment]
@sestinj Yes, I'm still interested, I can add a new version of zh-CN docs.

**Comment by sestinj** [comment]
@mayf09 awesome! I'll leave this up then and await further changes from you—or, given that a lot has changed, it may be easier to make a new PR if you'd like

**Comment by mayf09** [comment]
@sestinj I think make a new PR is better, and I will do it.

**Comment by sestinj** [comment]
Awesome! I will close this one then

**Pull request closed without merging**
