### PR TITLE
Offload all token counting to worker processes as well as some optimizations to do more token counting in parallel

### PR DESCRIPTION
**Pull request by spew**
## Description
This change moves all countTokens(...) calls into a workerpool, it makes the new bottleneck sqllite inserts.

Adding the workerpool logic broke gui as vite does not support __dirname or path.join(...). To work around this, moved the gui dependency of stripImages out of countTokens.ts

On my system, before this change, indexing the continue repo took about 9:30, after the change, it takes 7:30. However, there much less instances of "extension is not responsive" and similar errors in the VScode developer console logs. In addition, it makes the new bottleneck the rate of SQLite inserts.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

### CODE REVIEW

**Comment by spew** [comment]
I suspect if we can make sqllite inserts fast indexing will get 5-10x faster after this change.

**Comment by sestinj** [comment]
Did you run into this at all when doing `cd gui && npm run dev`



```
2:39:37 PM [vite] page reload tmp_index.html
2:39:44 PM [vite] Internal server error: Bindings not found.
  Plugin: vite:react-swc
  File: /Users/natesesti/Desktop/continue/gui/src/main.tsx
      at Compiler.<anonymous> (/Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:227:19)
      at Generator.next (<anonymous>)
      at /Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:31:71
      at new Promise (<anonymous>)
      at __awaiter (/Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:27:12)
      at Compiler.transform (/Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:203:16)
      at transform (/Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:352:21)
      at transformWithOptions (file:///Users/natesesti/Desktop/continue/gui/node_modules/@vitejs/plugin-react-swc/index.mjs:164:20)
      at TransformContext.transform (file:///Users/natesesti/Desktop/continue/gui/node_modules/@vitejs/plugin-react-swc/index.mjs:79:30)
      at Object.transform (file:///Users/natesesti/Desktop/continue/gui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44352:62)

```

**Comment by sestinj** [comment]
ok seems to be fixed by upgrading. not sure why this would have been affected

**Comment by sestinj** [comment]
This is great. A couple of notes, but I'm merging immediately anyway because it's working
- I added the step to copy the worker files into the jetbrains build as well in build.js
- I assume you only used worker pools for the llama tokenizer because tiktoken was entirely unproblematic in comparison?

**Comment by spew** [comment]
No, I actually started this work long before TikToken was added (or maybe it has always been there and I missed it?) so I think I need to revist this and have it do TikToken too.

**Comment by KingAmo** [comment]
> @spew Did you run into this at all when doing `cd gui && npm run dev`?
> 
> ```
> 2:39:37 PM [vite] page reload tmp_index.html
> 2:39:44 PM [vite] Internal server error: Bindings not found.
>   Plugin: vite:react-swc
>   File: /Users/natesesti/Desktop/continue/gui/src/main.tsx
>       at Compiler.<anonymous> (/Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:227:19)
>       at Generator.next (<anonymous>)
>       at /Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:31:71
>       at new Promise (<anonymous>)
>       at __awaiter (/Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:27:12)
>       at Compiler.transform (/Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:203:16)
>       at transform (/Users/natesesti/Desktop/continue/gui/node_modules/@swc/core/index.js:352:21)
>       at transformWithOptions (file:///Users/natesesti/Desktop/continue/gui/node_modules/@vitejs/plugin-react-swc/index.mjs:164:20)
>       at TransformContext.transform (file:///Users/natesesti/Desktop/continue/gui/node_modules/@vitejs/plugin-react-swc/index.mjs:79:30)
>       at Object.transform (file:///Users/natesesti/Desktop/continue/gui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44352:62)
> ```

same error, did you find  a solution ?

**Comment by spew** [comment]
Hi KingAmo, I apologize, I never ran that and struggled a lot with the local dev web server

**Pull request merged**
