### PR TITLE
Fixed Mocha tests + added debugging configurations to vscode

### LINKED ISSUE #353: [VSCode extension] Both npm run test and npm run jest fail
**To Reproduce**
Checkout main
```
cd extension
npm run package #  to install dependencies 
npm run test
npm run jest

npx tsc # Also fails - thus polluting regular project development even when not working on tests
```

**Expected behavior**
A single testing framework is chosen
Tests compile and succeed

**Suggested changes (playing around locally rn)**
- Remove jest - currently unused + seems like mocha is the default and more light weight testing environment for vscode extensions.
- Fix mocha tests so npm run test works
- Add testing to launch.json configuration for easy test debugging

**Environment**
- Operating System: MacOS
- Python Version: 3.11
- Node version: v19.9.0
- Continue Version: 0.0.266

**Console logs**
```
> continue@0.0.256 test
> node ./out/test/runTest.js

(node:66080) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/kirilldubovitskiy/projects/continue-draft-worktree/extension/out/test/runTest.js:1
import * as path from "path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1195:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.9.0
```

Jest (truncated)
```

 FAIL  src/activation/test/environmentSetup.test.ts
  ● Test suite failed to run

    src/activation/test/environmentSetup.test.ts:3:10 - error TS2305: Module '"../environmentSetup"' has no exported member 'getPythonPipCommands'.

    3 import { getPythonPipCommands } from "../environmentSetup";
               ~~~~~~~~~~~~~~~~~~~~
    src/activation/test/environmentSetup.test.ts:5:1 - error TS2304: Cannot find name 'jest'.

    5 jest.mock("os");
      ~~~~
    src/activation/test/environmentSetup.test.ts:6:1 - error TS2304: Cannot find name 'jest'.

    6 jest.mock("child_process");
```

### PR DESCRIPTION
**Pull request by bra1nDump**
# High Level
- npm run test now works and runs any .test.ts files as test suits across /src
- Added one click test debug to vscode (see screenshots) with ability to breakpoint in tests, code being tested and server 
- To step through extension code additional setup might be needed, but thats for later, the project currently does not have such tests

Fixes #353

# Details
- Adding a compound launch configuration for debugging tests + server
- Added a new esbuild for:
  - bundling test runners (run tests on vscode + mocha runner)
  - bundling all tests in the project
- Some opinionated renamings / moving test related things around
- Changed output directory in tsconfig to avoid overriding the entire out directory - bundles tests also go there

Breakpoints in tests work
image

Stepping into works
image

Breakpoints in server work
image

### CODE REVIEW

**Comment by bra1nDump** [comment]
Ugh, that lockfile with a different version is annoying, I will fix that up in a separate PR, should be a very small fix

**Comment by sestinj** [comment]
Sounds good. I'm going to pull this locally and do a bit of playing around myself before merging. I think it would be great to incorporate the testing into CI, but that will also probably be a separate PR.

**Comment by bra1nDump** [comment]
@sestinj feel free to push changes here before merging.
Side note: esm / cjs import / require differences is why I chose to use esbuild for tests (also mention it somewhere inline).

The test that starts the server is kind of flakey when running using npm run test. Haven't looked into it but would be needed to add to CI.

**Comment by sestinj** [comment]
Only changes I made were to allow longer for the python server to start up in the test (takes >10 seconds the first time typically, which is something I need to work on), and to change the default python interpreter to python3 instead of python, because VS Code on my machine didn't seem to like the symlink.

Merging now, this is a fantastic PR!

**Pull request merged**
