### PR TITLE
feat(embeddings): add gemini provider

### LINKED ISSUE #1346: [CON-239] Gemini Embeddings Provider
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Google Gemini offers text embeddings, and we don't yet have (built-in) support!

### Solution

https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding-and-embedding is their documentation.

The implementation of this feature would consist of
1. Copy the [CohereEmbeddingsProvider](https://github.com/continuedev/continue/blob/preview/core/indexing/embeddings/CohereEmbeddingsProvider.ts#L38-L53) into a new adjacent file, and rename GeminiEmbeddingsProvider
2. Alter the fetch request to fit what Google expects
3. Parse the response data to match the format that Continue expects
4. Add the class to the list [here](https://github.com/continuedev/continue/blob/preview/core/indexing/embeddings/index.ts#L8-L17)
5. Update `extensions/vscode/config_schema.json`

<sub>[CON-239](https://linear.app/continue/issue/CON-239/gemini-embeddings-provider)</sub>

### PR DESCRIPTION
**Pull request by Patrick-Erichsen**
closes #1346

## Description

Adds Gemini as an embeddings provider.

## Details

In addition to adding the Gemini embeddings provider, there's a few enhancements, linter fixes, typo fixes, etc:
- Moves common logic between embedding providers to the `BaseEmbeddingsProvider` class, e.g. batching and `id` getter
- Created `IBaseEmbeddingsProvider` interface to centralize typings 
- Installs `@google/generative-ai` as a devDependency in `core` to provide typings for the embedding request
- Fixes a table name typo in `docs/docs/walkthroughs/codebase-embeddings.md` and adds a section for the new Gemini provider
- Addresses a handful of linter errors, e.g. camelCasing var names
- Removes the constraint to provide a `model` config val for `ollama` provider since we provide a default value
- Fixes incorrect instructions in `CONTRIBUTING.md` to run `npm package`, should be `npm run package`
- Applies prettier formatting to `core/.eslintrc.json`

## Testing

1. [Get an API key for Gemini here](https://ai.google.dev/gemini-api/docs/api-key)
2. Update `~/.continue/config.json` to use the new provider
```json
"embeddingsProvider": {
    "provider": "gemini",
    "apiKey": "<GEMINI_API_KEY>"
 },
```
3. Temporarily comment out the `apiKey` config and confirm that you get a warning that reads `Missing property "apiKey".
`
4. Package and install the new extension
5. Confirm that indexing is successful

## Checklist

- [x] The base branch of this PR is `preview`, rather than `main`

### CODE REVIEW

**Comment by sestinj** [comment]
@Patrick-Erichsen great work! I think I like the BaseEmbeddingsProvider refactor : )

Only thing, I think a `tmp` file (just one) slipped through.

I'm trying to finish up a lot of extra work today and tomorrow so may not merge right away, but it looks ready

**Comment by Patrick-Erichsen** [comment]
> Only thing, I think a `tmp` file (just one) slipped through.

Good catch! That file has been removed from the PR with [af00cf1](https://github.com/continuedev/continue/pull/1362/commits/af00cf18d056cef7420e0dcba397e80de22f8804).

**Comment by Patrick-Erichsen** [comment]
@sestinj quick bump on this! Getting some merge conflicts I've patched a few times from my updates to `extensions/vscode/continue_rc_schema.json`.

Also on a side note, I noticed in a [recent blog post](https://ollama.com/blog/continue-code-assistant) that there were instructions on providing a model config for `ollama` as an embeddings provider:

```json
{
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text"
  }
}
```

This PR sets `nomic-embed-text` as the default model for `ollama`: https://github.com/continuedev/continue/pull/1362/files#diff-96619fcfa327044e38a916958583dd33afca3ee20d6ef339d103b151da1d39b5R32-R35. So in the future a user could just configure `ollama` as their embeddings provider without specifying the model:

```json
{
  "embeddingsProvider": {
    "provider": "ollama"
  }
}
```

**Review by sestinj — APPROVED** [review]

**Comment by sestinj** [comment]
@Patrick-Erichsen nice work, and thanks for dealing with the merge conflicts! Definitely a great idea to set a default for Ollama as well

**Pull request merged**
