### PR TITLE
Code highlights ala Paul Gauthier's repomap technique from Aider Chat

### PR DESCRIPTION
**Pull request by restlessronin**
All of the plumbing is working now, but the library still needs a little work. The tag query files for typescript, which I used for testing, are returning 0 defs in many case. This needs to be cleaned up and fixed on the library side, but having the base ContextProvider code in the repo makes it easier to sync with the latest version of the preview branch, and continue testing to improve the provider.

### CODE REVIEW

**Comment by sestinj** [comment]
This is awesome. Putting all my time toward shipping tab-autocomplete at the very moment, but will have some ideas to share as soon as that's done

**Comment by restlessronin** [comment]
Look forward to it. I'm still getting to know all the moving pieces of Continue so I can try different experiments.

**Comment by sestinj** [comment]
Alr this is gorgeous. I had wondered how the PR was so compact, then I realized you wrote the NPM package. Love it!

One question: why the import("...") instead of import {} from "..." at the top of the context provider file? Probably doesn't change anything, wanted to check whether you had done this because of our docs about dynamic imports or not.

I'm of course going to test this a bit locally, and have a handful of changes I'm making today that will change how configs are loaded, so I think it's best to just wait and do the testing in that new setup. So I'm gonna get back to work on finishing that up, then will merge this immediately following the merge of that other work

**Comment by sestinj** [comment]
🚀

**Comment by restlessronin** [comment]
> Alr this is gorgeous. I had wondered how the PR was so compact, then I realized you wrote the NPM package. Love it!

Thank you!

> 
> One question: why the import("...") instead of import {} from "..." at the top of the context provider file? Probably doesn't change anything, wanted to check whether you had done this because of our docs about dynamic imports or not.
>

I believe it was because of a comment to that effect (dynamic imports) on the discord server.

**Pull request merged**
