### PR TITLE
Turn of chunking for files with more than 1m characters and files lacking extensions

### PR DESCRIPTION
**Pull request by spew**
## Description

This should help with some of the unnecessary work being done in indexing

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

### CODE REVIEW

**Comment by Patrick-Erichsen** [comment]
Good heuristics 👍

**Comment by Patrick-Erichsen** [comment]
Screenshot 2024-08-09 at 1 06 07 PM

GH says there are merge conflicts but strangely is not showing what they actually are.

**Comment by fry69** [comment]
Local merge into the current `dev` branch produces this error:
```shell
$ git merge chunking 
Auto-merging core/indexing/CodebaseIndexer.ts
Auto-merging core/indexing/LanceDbIndex.ts
Auto-merging core/indexing/chunk/chunk.ts
CONFLICT (modify/delete): core/test/indexing/CodebaseIndexer.skip.ts deleted in HEAD and
modified in chunking.  Version chunking of core/test/indexing/CodebaseIndexer.skip.ts
left in tree.
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by Patrick-Erichsen** [comment]
Thanks for checking that out @fry69. 

@spew - the conflicting file can be deleted since Nate unskipped the test in this commit: https://github.com/continuedev/continue/pull/1979

**Comment by spew** [comment]
Done.

**Review by sestinj — APPROVED** [review]

**Comment by sestinj** [comment]
And a new era of testing has begun! Nice work

**Pull request merged**
