### PR TITLE
IBM watsonx provider branding & software support

### PR DESCRIPTION
**Pull request by NoeSamaille**
## Description

- Fixed IBM watsonx provider branding.
- Adds support for watsonx software instance, including ZenApiKey.
- Refactors `ConfigureProvider.tsx` removing updates specific to watsonx by aggregating credentials parameters into one param regardless of type (ApiKey, ZenApiKey, or `username:password`).
- Provides documentation in watsonx Provider Long Description on how to get started and authenticate.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Screenshots

Screenshot 2024-08-21 at 09 41 53

## Testing

N/A

### CODE REVIEW

**Comment by remiserra** [comment]
**Suggestion** : Replace `API Key` with `ZenApiKey` to avoid confusion with the IBM Cloud API key:
in [watsonx.md](https://github.com/NoeSamaille/continue/blob/watsonx-branding-sw/docs/docs/reference/Model%20Providers/watsonx.md#watsonxai-software) and in [providers.ts](https://github.com/NoeSamaille/continue/blob/watsonx-branding-sw/gui/src/pages/AddNewModel/configs/providers.ts), in the long description , section **watsonx.ai Software**, *Option 2* : 
`2. *Option 2*: using API Key authentication:`
=>
`2. *Option 2*: using ZenApiKey authentication:`

**Comment by NoeSamaille** [comment]
@remiserra done :)

**Comment by ajshedivy** [comment]
This PR addresses changes suggested in draft #2045

**Comment by NoeSamaille** [comment]
After discussion with several IBM folks we agreed this PR is now ready for review :)

@Patrick-Erichsen @sestinj FYI

**Review by rishacha — COMMENTED** [review]
This line requires a change - https://github.com/continuedev/continue/blob/37702e17e27f00b2e7ea57a347ea38b263803acc/docs/docs/reference/Model%20Providers/watsonx.md?plain=1#L38

**Comment by B-Rajpal** [comment]
I think this needs a continue button after adding model params like model id

https://github.com/user-attachments/assets/02cbab64-c5e8-4b92-9632-424773c0c5db

**Comment by sestinj** [comment]
Thanks for the awesome work y'all! It looks mostly good to me, I'm going to pull down for final testing, but we'll aim to merge this right after we make our next release today

**Comment by sestinj** [comment]
Hi @NoeSamaille, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by NoeSamaille** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
