### PR TITLE
Revert "zh-CN docs"

### PR DESCRIPTION
**Pull request by vadjs**
Reverts continuedev/continue#2897

This PR broke the pipelines. I propose to revert it and leave comment to fix the original PR.

### CODE REVIEW

**Comment by sestinj** [comment]
@vadjs I prefer to simply fix the links. This was really large effort by the contributor and it's not too difficult to adjust them ourselves. Is this something you want to attempt? Otherwise I'm happy to do it myself

**Comment by sestinj** [comment]
Also @mayf09 in case you have any quick ideas about the solution to this

**Comment by mayf09** [comment]
Okay, what's the problem?

**Comment by vadjs** [comment]
@sestinj it makes sense, sure.
Closed my PR. 

> Is this something you want to attempt?
Not sure, I'm not really familiar with the docs side of the project yet. But i will be happy to see how PR with fix look like.

**Comment by sestinj** [comment]
Sorry I missed this, but I just ended up fixing it tonight

**Pull request closed without merging**
