### PR TITLE
test: Add basic unit test to baseLLM

### PR DESCRIPTION
**Pull request by inimaz**
## Description

Related to [#15](https://github.com/continuedev/contribution-ideas/issues/15). Adding unit test to the base abstract class of BaseLLM.

### CODE REVIEW

**Comment by sestinj** [comment]
@inimaz love this! Did you want to fill in some of the TODOs first, or can I go ahead and merge?

**Comment by inimaz** [comment]
Nice! @sestinj Go ahead and merge! I added the TODOs to leave it if someone else wants to *continue*.
If I have time I can keep on on a future PR.

**Comment by sestinj** [comment]
Perfect, thanks so much for starting this!

**Comment by sestinj** [comment]
Hi @inimaz, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by inimaz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
