### PR TITLE
feat(#898): add Jira api v2 support

### LINKED ISSUE #898: Add support for Jira REST API version 2
Jira datacenter version only supports REST API v2.

**Actions**
- Investigate the differences between REST API v2 and v3
- Add a parameter to the settings to specify an API version
  - If no parameter is provided, default to v3
- Create a helper that abstracts the differences between v2 and v3
- Update documentation
- Update schema

**References**
- [Jira Data Center REST API](https://docs.atlassian.com/software/jira/docs/api/REST/9.14.0/)

_Originally posted by @benedict-lee in https://github.com/continuedev/continue/issues/860#issuecomment-1965883778_

### PR DESCRIPTION
**Pull request by theBenForce**
Closes #898

### CODE REVIEW

**Comment by sestinj** [comment]
@theBenForce This is great work! We prefer to take all PRs through the preview branch so that they have a chance to be tested in the pre-release extension before going fully live. Would you be able to make this PR against the preview branch instead? This is also important because I made a small handful of changes to your original PR (mostly with regards to the importing of the adf-to-md library

**Comment by sestinj** [comment]
@theBenForce Thank you! Assuming it's mostly ready, would you like me to handle the few merge conflicts? Happy to do so

**Comment by theBenForce** [comment]
I haven't had a chance to test it yet, I wanted to make sure I didn't break anything before it got merged.

**Comment by theBenForce** [comment]
I just verified that my updates work with both the v2 and v3 API.

**Comment by theBenForce** [comment]
Should be ready for review @sestinj, I've verified it works with v2 and v3 APIs. Let me know if I need to update anything else.

**Comment by sestinj** [comment]
@theBenForce accidentally merged before asking this, but is there anything else that needs to be added to the documentation? Using my same config from before gives a 404

**Comment by theBenForce** [comment]
@sestinj you'll have to set `apiVersion` to `"2"` since you're not on API v3.

**Pull request merged**
