### PR TITLE
Clarifying `logs` instructions in troubleshooting.md

### PR DESCRIPTION
**Pull request by amihalik**
I was walking through your `troubleshooting.md` guide and noticed an error and was slightly confused about one of the steps (I had never used the "dev tools" window in VS Code).  I made some minor edits that clarified/corrected the "logs" section.

### CODE REVIEW

**Comment by sestinj** [comment]
Thanks, this is a good clarification. I'm changing just one thing (not making the "View Continue Server Logs" -> "Toggle Developer Tools" update) because this is actually a separate thing intended to be there (opens a separate log file for just the Continue server's logs)

**Comment by sestinj** [comment]
Since you were on the troubleshooting page, did everything get worked out, or are there still any remaining problems?

**Comment by sestinj** [comment]
Hi @amihalik, yesterday we shared [some updates](https://discordapp.com/channels/1108621136150929458/1131313996750917835/1371996789967687783) with our contributors about how we're aiming to improve the contribution process. Part of this included the addition of a [Contributor License Agreement](https://github.com/continuedev/continue/blob/main/docs/docs/CLA.md) (CLA) to protect both contributors and the project. We're reaching out to ask that previous contributors sign it.

Could you please take a moment to sign, or if you have any questions send me a message? (either here or nate@continue.dev would work)

To do so, you just need to **post a comment below with the following text:**<br/>
```
I have read the CLA Document and I hereby sign the CLA
```

❤️ Thank you for the work you've done on Continue, and let me know if you have any suggestions on how we can make the project even better!

**Comment by amihalik** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
