### PR TITLE
Fix streaming into next session bug

### PR DESCRIPTION
**Pull request by RomneyDa**
## Description

Streaming was not getting aborted on loading a new session

Fixed with global stream abort

To duplicate on current main, say "write me a long story", go to history, and then select a different session. It will continue streaming into the newly loaded sessioon

### CODE REVIEW

**Comment by Patrick-Erichsen** [comment]
Resolved merge conflicts from my recent pushes

**Review by sestinj — DISMISSED** [review]

**Comment by sestinj** [comment]
@Patrick-Erichsen I think PR checks are failing from the merge

**Comment by Patrick-Erichsen** [comment]
Correct, pushed a fix for that.

**Comment by sestinj** [comment]
thanks you

**Pull request merged**
