### PR TITLE
Implement disableIndexing check and improve search result handling in useSubmenuContextProviders

### PR DESCRIPTION
**Pull request by samir-abis-everest**
This PR introduces a check for the `disableIndexing` setting and improves the handling of search results in the `useSubmenuContextProviders` hook. Key changes include:

1. Added a check for `disableIndexing` to skip the file context provider when indexing is disabled.
2. Improved error handling and logging throughout the component.
3. Implemented a loading state for initial data fetch.
4. Added timeout handling for the `loadSubmenuItems` function.
5. Enhanced debugging with more detailed console logs.
6. Implemented an auto-reload mechanism triggered by `refreshSubmenuItems`.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Screenshots

N/A (No visual changes)

## Testing

1. Enable and disable the `disableIndexing` setting in local storage and verify that the file context provider is skipped when disabled.
2. Test the search functionality with various queries to ensure results are returned correctly.
3. Verify that the loading state is displayed while initial data is being fetched.
4. Test the timeout handling by artificially delaying the `context/loadSubmenuItems` response.
5. Trigger a `refreshSubmenuItems` event and verify that the data is reloaded correctly.
6. Check the console logs for the new debug information and ensure no unexpected errors are occurring.

### CODE REVIEW

**Comment by samir-abis-everest** [comment]
todo: add `repo-map`

**Comment by Patrick-Erichsen** [comment]
Hey @samir-abis-everest , could you walk me through how you were setting `disableIndexing`? I attempted to update my config.json with `"disableIndexing": true` but am still seeing the file context provider. I see that we're setting the value in localStorage from the value in config.json so my assumption is that this should have disabled the file context provider.

**Comment by samir-abis-everest** [comment]
> Hey @samir-abis-everest , could you walk me through how you were setting `disableIndexing`? I attempted to update my config.json with `"disableIndexing": true` but am still seeing the file context provider. I see that we're setting the value in localStorage from the value in config.json so my assumption is that this should have disabled the file context provider.

Hi @Patrick-Erichsen , I enabled it through a `.continuerc.json`.

**Comment by samir-abis-everest** [comment]
# Version Update and Performance Optimizations

This commit includes the following changes:

1. Introduced `IndexedProvider` enum for improved type safety.
2. Implemented performance optimizations:
   - Memoized `getOpenFileItems` function to prevent unnecessary re-renders.
   - Used `useCallback` for the `addItem` function.
3. Enhanced `useEffect` cleanup for refreshing open files.
4. Added immediate call to `refreshOpenFiles()` on component mount.
5. Improved type checking for provider types using the new enum.

These changes aim to enhance performance, type safety, and overall code robustness while maintaining core functionality.

**Comment by Patrick-Erichsen** [comment]
@samir-abis-everest thanks for the follow up here - I'm still unable to get the context providers to not register in the submenu however, including after creating a `.continuerc.json` with the following content:

```json
{
  "disableIndexing": true
}

Here's a screenshot of what I'm seeing, note that the debug logs are showing that we are skipping "file" and "code" providers, but the submenu is still displaying them.

<img width="1463" alt="Screenshot 2024-09-02 at 2 00 29 PM" src="https://github.com/user-attachments/assets/0bfb593b-b6ef-49d1-9f5f-741d77faafc1">

Also, I tried to commit a small commit that adds a `dependsOnIndexing` instead of using the new enum, but am having an issue committing back to your branch, so if you don't mind applying this small patch that would be appreciated 👍 

[diff.patch](https://github.com/user-attachments/files/16841284/diff.patch)

**Comment by samir-abis-everest** [comment]
Displaying them is normal since in your configuration they're set. They're disabled though, which is good 👍 . We can definitely improve this in a next patch where if there is indexing disabled we shouldn't show these context providers.

I'll take a look at the patch and add it to the PR

**Comment by Patrick-Erichsen** [comment]
Got it, disabling them in the meantime is a great fix that solves the root issue. Thanks for making those changes and seeing this one through! 🚀

**Comment by samir-abis** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Pull request merged**
