### PR TITLE
fix code context description parsing to filename & range

### PR DESCRIPTION
**Pull request by todd-xander**
## Description

Fix code context item description (including a range string as suffix) parsing error.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

## Screenshots

[ For visual changes, include screenshots. ]

## Testing

[ For new or modified features, provide step-by-step testing instructions to validate the intended behavior of the change. ]

### CODE REVIEW

**Comment by sestinj** [comment]
@todd-xander thanks for the PR! Can you share a bit more background on the problem that this solves? If you can point me toward the error and how to reproduce I'll be able to better evaluate this

**Comment by todd-xander** [comment]
> @todd-xander thanks for the PR! Can you share a bit more background on the problem that this solves? If you can point me toward the error and how to reproduce I'll be able to better evaluate this

In case of attaching a code snippet as context, it set `description` in `ContextItem` in format `{{filepath}} ({{range}})`, and set as a code block fance tag when rendering markdown, it leads to remark parsing result as `language={{filepath}} meta={{rang}}`, cause rendering abnormal, and showFile not work.

**Comment by sestinj** [comment]
What do you mean by "rendering abnormal"?

**Review by sestinj — APPROVED** [review]

**Comment by sestinj** [comment]
I understand this now, thank you very much for the PR!

**Pull request merged**
