### PR TITLE
Add `maxBatchSize` option for EmbeddingsProvider.

### PR DESCRIPTION
**Pull request by YouJiacheng**
## Description

Add `maxBatchSize` option for EmbeddingsProvider.

Minor changes:
+ fix a bug in getBatchedChunks: `if (chunks.length > this.maxBatchSize) return [chunks]` causes chunks will never be spilt into multiple batches. Originally only Gemini uses it, and its `maxBatchSize` is 2048, so no problem in the most of cases.      
+ consolidate duplicated code implementing `getBatchedChunks` logic in` CohereEmbeddingsProvider`, `FreeTrialEmbeddingsProvider`, `HuggingFaceTEIEmbeddingsProvider` and `OpenAIEmbeddingsProvider`. `TransformersJsEmbeddingsProvider` has identical logic, but its property is called `maxGroupSize`.

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [ ] The relevant docs, if any, have been updated or created

## Screenshots

[ For visual changes, include screenshots. ]

## Testing

[ For new or modified features, provide step-by-step testing instructions to validate the intended behavior of the change. ]

### CODE REVIEW

**Comment by Patrick-Erichsen** [comment]
Thanks for looking into this @YouJiacheng ! I had noticed that logic error in `getBatchedChunks` yesterday. Nice cleanup to consolidate the logic for the other providers as well.

Getting an error in `core/indexing/embeddings/HuggingFaceTEIEmbeddingsProvider.ts` after this update however: https://github.com/continuedev/continue/actions/runs/10672135505/job/29624337029?pr=2163#step:12:6

@sestinj @YouJiacheng - thoughts on defining a `DEFAULT_MAX_BATCH_SIZE` in the base class? I'm not sure if it's better to define an arbitrarily small max batch, or go with something like `Number.MAX_SAFE_INTEGER`.

Either way I would +1 the [comment here](https://github.com/continuedev/continue/issues/2162#issue-2501372689) that we should add it to the docs. 

@YouJiacheng , mind updating this PR with that documentation once we come to a conclusion?

**Comment by YouJiacheng** [comment]
> Getting an error in core/indexing/embeddings/HuggingFaceTEIEmbeddingsProvider.ts after this update however

>  indexing/embeddings/HuggingFaceTEIEmbeddingsProvider.ts(12,3): error TS2610: 'maxBatchSize' is defined as an accessor in class 'BaseEmbeddingsProvider', but is overridden here in 'HuggingFaceTEIEmbeddingsProvider' as an instance property.

I realized there will be such an error after I opened this PR several ours. I only implemented a getter for `maxBatchSize` in `BaseEmbeddingsProvider`, while `HuggingFaceTEIEmbeddingsProvider` will modify it in its custom handling logic.

It was the first time I wrote TypeScript and I forgot to read `CONTRIBUTING.md` so I didn't test it locally. Is it okay to exercise CI or I should test it locally?

Do you think we should add a `_maxBatchSize` property (not sure if it can be private) and implement a setter in the base class? That's not very elegant. Or we can override the getter in `HuggingFaceTEIEmbeddingsProvider` and add a private property `_maxBatchSize`.

**Comment by YouJiacheng** [comment]
I got `tsc core` passed locally. Not sure about whether we should further consolidate the logic: now most `embed` are similar.
image
image
image

**Review by sestinj — APPROVED** [review]
I would be fine to merge this now, but I also support further consolidating the logic

**Comment by sestinj** [comment]
I'm going to merge this now and if we want to move the logic all to the base class we can do that in a separate PR

**Review by sestinj — APPROVED** [review]

**Comment by YouJiacheng** [comment]
Oh I forgot to update `config_schema.json`
https://github.com/continuedev/continue/blob/455ca6bde068f3ebbfff225b5ed428b2da16d1a7/extensions/vscode/config_schema.json#L2110-L2116

**Pull request merged**
