### PR TITLE
[CON] docs layout refactor

### PR DESCRIPTION
**Pull request by priyashpatil**
## Description

- This PR brings intended layout refactor related to #1887
- Top level community nav link and sidebar.
- More config references under reference. 
- Advanced section 
- Tutorial section

> Remaining docs rewrite is coming in next PR

## Checklist

- [x] The base branch of this PR is `dev`, rather than `main`
- [x] The relevant docs, if any, have been updated or created

### CODE REVIEW

**Comment by sestinj** [comment]
Nice! Excited to take a closer look later today!

**Comment by sestinj** [comment]
@TyDunn also should take a look

**Comment by sestinj** [comment]
@priyashpatil Thanks for putting all of the work in here—I'm starting with some initial feedback on the copy within the pages. I know Ty also wants to spend some more time reviewing structure and adding his 2 cents, so can we pause on the next parts of work that you have planned until we have that ironed out? Want to avoid you doing duplicate work

**Comment by priyashpatil** [comment]
> @priyashpatil Thanks for putting all of the work in here! I'm starting with some initial feedback on the copy within the pages. I know Ty also wants to spend some more time reviewing structure and adding his 2 cents, so can we pause on the next parts of work that you have planned until we have that ironed out? Want to avoid you doing duplicate work

Yep works. 👍

**Comment by sestinj** [comment]
Cool, thanks. I do think we're probably going to want to take on writing most of the docs language ourselves, largely because this is such a core part of Continue. Will share updates later next week!

**Comment by sestinj** [comment]
@priyashpatil FYI we've now moved the docs work which was inspired by this over to the docs-refactor branch and are approaching a PR soon! Going to close this so we can focus on having it all in one place

**Pull request closed without merging**
