### PR TITLE
feat: add Jira context provider

### PR DESCRIPTION
**Pull request by theBenForce**
I implemented this as a `CustomContextProvider` and it works great. I can't figure out how to get the extension running in debug mode to verify it. If someone who has a working setup can verify I would appreciate it, otherwise I will test it sometime in the next week or two.

### CODE REVIEW

**Comment by theBenForce** [comment]
Finally got this working. I had to run `./install-dependencies.sh` inside WSL _before_ opening in vscode.

image

**Comment by sestinj** [comment]
@theBenForce this is awesome! I'm going to give it a run in the next couple of days before merging, but from a quick look it looks like you did everything right.

**Comment by theBenForce** [comment]
@sestinj thanks! The one thing I wasn't sure of was where to place the ticket key and summary in the title/description. I like that having both in the title allows me to see both in the suggestion list.

**Comment by sestinj** [comment]
@theBenForce I think what you did makes sense there. I'm going to merge as everything looks good, but if I find anything wrong in testing I'll circle back to this PR. Seriously excited about this feature, thanks for the great work!!!

**Comment by sestinj** [comment]
@theBenForce Works like a charm! I set up my own Jira account just for this, and everything basically worked first try! Only change I ended up making was to upgrade the adf2md package: https://github.com/continuedev/continue/commit/8223ba25a82c6641326252845ef1b0f53c62a6ee

Thanks again!

**Comment by benedict-lee** [comment]
@theBenForce @sestinj Can this be improved to work with the jira datacenter version?
I set up a jira domain, but the jira DC version I'm using has a different api endpoint, so I can't use it.
jira reat api endpoint `rest/api/3` is not supported.
v3(beta) api is only available in jira cloud 

- jira datacenter verser : 9.4.7
- supported api endpoint : JIRA_HOST/rest/api/2 or JIRA_HOST/rest/api/latest

**Pull request merged**
